### ISSUE TITLE
Using starter from behind corporate proxy

### ISSUE THREAD

**Issue by faceleg** [prismicio/javascript-nodejs-starter#15]
Is there a configuration option I can use to set the proxy?

**Comment by erwan** [comment]
Not really. Are you using the kit in-browser or in a Node.js app?

**Comment by faceleg** [comment]
Node js - what underlying request module is used? I've had this issue with a few high level modules, one I fixed by sniffing for and passing the HTTP_PROXY value to the underlying request module (they don't all check for and use this automagically)

**Comment by erwan** [comment]
we're using http/https:

https://github.com/prismicio/javascript-kit/blob/master/src/utils.js#L103

**Comment by faceleg** [comment]
Thanks, that's what I needed. Time permitting I'll fix this in a PR.

**Comment by erwan** [comment]
That'd be awesome!
